// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package sqlcdb

import "context"

const listarInversiones = `-- name: ListarInversiones :many
SELECT
    id,
    nombre,
    monto_inicial,
    monto_actual,
    rendimiento_esperado,
    estado,
    tipo_inversion_id,
    destino_inversion_id
FROM inversiones
`

func (q *Queries) ListarInversiones(ctx context.Context) ([]Inversion, error) {

	rows, err := q.db.QueryContext(ctx, listarInversiones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Inversion

	for rows.Next() {

		var i Inversion

		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.MontoInicial,
			&i.MontoActual,
			&i.RendimientoEsperado,
			&i.Estado,
			&i.TipoInversionID,
			&i.DestinoInversionID,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

const buscarInversionPorID = `-- name: BuscarInversionPorID :one
SELECT
    id,
    nombre,
    monto_inicial,
    monto_actual,
    rendimiento_esperado,
    estado,
    tipo_inversion_id,
    destino_inversion_id
FROM inversiones
WHERE id = ?
`

func (q *Queries) BuscarInversionPorID(ctx context.Context, id int64) (Inversion, error) {

	row := q.db.QueryRowContext(ctx, buscarInversionPorID, id)

	var i Inversion

	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MontoInicial,
		&i.MontoActual,
		&i.RendimientoEsperado,
		&i.Estado,
		&i.TipoInversionID,
		&i.DestinoInversionID,
	)

	return i, err
}

const crearInversion = `-- name: CrearInversion :one
INSERT INTO inversiones (
    nombre,
    monto_inicial,
    monto_actual,
    rendimiento_esperado,
    estado,
    tipo_inversion_id,
    destino_inversion_id
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    nombre,
    monto_inicial,
    monto_actual,
    rendimiento_esperado,
    estado,
    tipo_inversion_id,
    destino_inversion_id
`

type CrearInversionParams struct {
	Nombre              string
	MontoInicial        float64
	MontoActual         float64
	RendimientoEsperado float64
	Estado              string
	TipoInversionID     int64
	DestinoInversionID  int64
}

func (q *Queries) CrearInversion(ctx context.Context, arg CrearInversionParams) (Inversion, error) {

	row := q.db.QueryRowContext(
		ctx,
		crearInversion,
		arg.Nombre,
		arg.MontoInicial,
		arg.MontoActual,
		arg.RendimientoEsperado,
		arg.Estado,
		arg.TipoInversionID,
		arg.DestinoInversionID,
	)

	var i Inversion

	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MontoInicial,
		&i.MontoActual,
		&i.RendimientoEsperado,
		&i.Estado,
		&i.TipoInversionID,
		&i.DestinoInversionID,
	)

	return i, err
}

const actualizarInversion = `-- name: ActualizarInversion :one
UPDATE inversiones
SET
    nombre = ?,
    monto_inicial = ?,
    monto_actual = ?,
    rendimiento_esperado = ?,
    estado = ?,
    tipo_inversion_id = ?,
    destino_inversion_id = ?
WHERE id = ?
RETURNING
    id,
    nombre,
    monto_inicial,
    monto_actual,
    rendimiento_esperado,
    estado,
    tipo_inversion_id,
    destino_inversion_id
`

type ActualizarInversionParams struct {
	Nombre              string
	MontoInicial        float64
	MontoActual         float64
	RendimientoEsperado float64
	Estado              string
	TipoInversionID     int64
	DestinoInversionID  int64
	ID                  int64
}

func (q *Queries) ActualizarInversion(
	ctx context.Context,
	arg ActualizarInversionParams,
) (Inversion, error) {

	row := q.db.QueryRowContext(
		ctx,
		actualizarInversion,
		arg.Nombre,
		arg.MontoInicial,
		arg.MontoActual,
		arg.RendimientoEsperado,
		arg.Estado,
		arg.TipoInversionID,
		arg.DestinoInversionID,
		arg.ID,
	)

	var i Inversion

	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MontoInicial,
		&i.MontoActual,
		&i.RendimientoEsperado,
		&i.Estado,
		&i.TipoInversionID,
		&i.DestinoInversionID,
	)

	return i, err
}

const borrarInversion = `-- name: BorrarInversion :execrows
DELETE FROM inversiones
WHERE id = ?
`

func (q *Queries) BorrarInversion(
	ctx context.Context,
	id int64,
) (int64, error) {

	result, err := q.db.ExecContext(
		ctx,
		borrarInversion,
		id,
	)

	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}
