// Code generated by sqlc. DO NOT EDIT.
package sqlcdb

// Estos structs los genera sqlc a partir de db/schema.sql.
// OJO: NO son los models del dominio.
// Fíjense que los IDs usan int64 y no int.
// Por esa razón el repositorio/adaptador debe mapear entre
// sqlcdb.Inversion y models.Inversion.

type Inversion struct {
	ID                  int64
	Nombre              string
	MontoInicial        float64
	MontoActual         float64
	RendimientoEsperado float64
	Estado              string
	TipoInversionID     int64
	DestinoInversionID  int64
}

type TipoInversion struct {
	ID          int64
	Nombre      string
	Descripcion string
}

type DestinoInversion struct {
	ID          int64
	Nombre      string
	Descripcion string
}

type Aporte struct {
	ID          int64
	InversionID int64
	Nombre      string
	Monto       float64
}
