// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
)

type Asistencia struct {
	ID           int64
	EventoID     int64
	EstudianteID int64
	Presente     sql.NullInt64
	HoraRegistro sql.NullString
}

type CategoriasEvento struct {
	ID          int64
	Nombre      string
	Descripcion sql.NullString
}

type Evento struct {
	ID          int64
	Nombre      string
	Descripcion sql.NullString
	Fecha       sql.NullString
	Lugar       sql.NullString
	Capacidad   sql.NullInt64
	CategoriaID sql.NullInt64
	Organizador sql.NullString
	Estado      sql.NullString
}

// Estos structs los genera sqlc a partir de db/schema.sql.
// OJO: NO son los models del dominio.
// Fíjense que los IDs usan int64 y no int.
// Por esa razón el repositorio/adaptador debe mapear entre
// sqlcdb.Inversion y models.Inversion.

type Inversion struct {
	ID                  int64
	Nombre              string
	MontoInicial        float64
	MontoActual         float64
	RendimientoEsperado float64
	Estado              string
	TipoInversionID     int64
	DestinoInversionID  int64
}

type TipoInversion struct {
	ID          int64
	Nombre      string
	Descripcion string
}

type DestinoInversion struct {
	ID          int64
	Nombre      string
	Descripcion string
}

type Aporte struct {
	ID          int64
	InversionID int64
	Nombre      string
	Monto       float64
}
