// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
)

type Asistencia struct {
	ID           int64
	EventoID     int64
	EstudianteID int64
	Presente     sql.NullInt64
	HoraRegistro sql.NullString
}

type CategoriasEvento struct {
	ID          int64
	Nombre      string
	Descripcion sql.NullString
}

type Evento struct {
	ID          int64
	Nombre      string
	Descripcion sql.NullString
	Fecha       sql.NullString
	Lugar       sql.NullString
	Capacidad   sql.NullInt64
	CategoriaID sql.NullInt64
	Organizador sql.NullString
	Estado      sql.NullString
}
