// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const actualizarEvento = `-- name: ActualizarEvento :one
UPDATE eventos
SET
  nombre = ?,
  descripcion = ?,
  fecha = ?,
  lugar = ?,
  capacidad = ?,
  categoria_id = ?,
  organizador = ?,
  estado = ?
WHERE id = ?
RETURNING id, nombre, descripcion, fecha, lugar, capacidad, categoria_id, organizador, estado
`

type ActualizarEventoParams struct {
	Nombre      string
	Descripcion sql.NullString
	Fecha       sql.NullString
	Lugar       sql.NullString
	Capacidad   sql.NullInt64
	CategoriaID sql.NullInt64
	Organizador sql.NullString
	Estado      sql.NullString
	ID          int64
}

func (q *Queries) ActualizarEvento(ctx context.Context, arg ActualizarEventoParams) (Evento, error) {
	row := q.db.QueryRowContext(ctx, actualizarEvento,
		arg.Nombre,
		arg.Descripcion,
		arg.Fecha,
		arg.Lugar,
		arg.Capacidad,
		arg.CategoriaID,
		arg.Organizador,
		arg.Estado,
		arg.ID,
	)
	var i Evento
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Fecha,
		&i.Lugar,
		&i.Capacidad,
		&i.CategoriaID,
		&i.Organizador,
		&i.Estado,
	)
	return i, err
}

const borrarEvento = `-- name: BorrarEvento :execrows
DELETE FROM eventos WHERE id = ?
`

func (q *Queries) BorrarEvento(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarEvento, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarEventoPorID = `-- name: BuscarEventoPorID :one
SELECT id, nombre, descripcion, fecha, lugar, capacidad, categoria_id, organizador, estado FROM eventos WHERE id = ?
`

func (q *Queries) BuscarEventoPorID(ctx context.Context, id int64) (Evento, error) {
	row := q.db.QueryRowContext(ctx, buscarEventoPorID, id)
	var i Evento
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Fecha,
		&i.Lugar,
		&i.Capacidad,
		&i.CategoriaID,
		&i.Organizador,
		&i.Estado,
	)
	return i, err
}

const crearEvento = `-- name: CrearEvento :one
INSERT INTO eventos (
  nombre, descripcion, fecha, lugar, capacidad, categoria_id, organizador, estado
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, nombre, descripcion, fecha, lugar, capacidad, categoria_id, organizador, estado
`

type CrearEventoParams struct {
	Nombre      string
	Descripcion sql.NullString
	Fecha       sql.NullString
	Lugar       sql.NullString
	Capacidad   sql.NullInt64
	CategoriaID sql.NullInt64
	Organizador sql.NullString
	Estado      sql.NullString
}

func (q *Queries) CrearEvento(ctx context.Context, arg CrearEventoParams) (Evento, error) {
	row := q.db.QueryRowContext(ctx, crearEvento,
		arg.Nombre,
		arg.Descripcion,
		arg.Fecha,
		arg.Lugar,
		arg.Capacidad,
		arg.CategoriaID,
		arg.Organizador,
		arg.Estado,
	)
	var i Evento
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Fecha,
		&i.Lugar,
		&i.Capacidad,
		&i.CategoriaID,
		&i.Organizador,
		&i.Estado,
	)
	return i, err
}

const listarEventos = `-- name: ListarEventos :many

SELECT id, nombre, descripcion, fecha, lugar, capacidad, categoria_id, organizador, estado FROM eventos
`

// EVENTOS
func (q *Queries) ListarEventos(ctx context.Context) ([]Evento, error) {
	rows, err := q.db.QueryContext(ctx, listarEventos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evento
	for rows.Next() {
		var i Evento
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Fecha,
			&i.Lugar,
			&i.Capacidad,
			&i.CategoriaID,
			&i.Organizador,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
